import { writeFileSync, existsSync, mkdirSync, unlinkSync, readFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import { DEFAULT_PORT } from "@claude-blocker/shared";

const PLUGIN_DIR = join(homedir(), ".config", "opencode", "plugin");
const PLUGIN_PATH = join(PLUGIN_DIR, "claude-blocker.ts");

const PLUGIN_CONTENT = `// Claude Blocker Plugin for OpenCode
// Auto-generated by claude-blocker --setup

export const ClaudeBlocker = async ({ $ }: { $: any }) => {
  const SERVER_URL = "http://localhost:${DEFAULT_PORT}/hook";

  const sendHook = async (event: string, extra?: Record<string, unknown>) => {
    const payload = JSON.stringify({
      session_id: process.env.OPENCODE_SESSION_ID || \`opencode-\${Date.now()}\`,
      hook_event_name: event,
      ...extra,
    });
    try {
      await $\`curl -s -X POST \${SERVER_URL} -H 'Content-Type: application/json' -d \${payload}\`.quiet();
    } catch {
      // Server might not be running, ignore errors
    }
  };

  return {
    "session.created": async () => {
      await sendHook("SessionStart");
    },
    "session.deleted": async () => {
      await sendHook("SessionEnd");
    },
    "session.idle": async () => {
      await sendHook("Stop");
    },
    "tool.execute.before": async (input: { tool?: string }) => {
      await sendHook("PreToolUse", { tool_name: input.tool });
    },
  };
};
`;

export function setupOpenCodePlugin(): void {
  // Ensure plugin directory exists
  if (!existsSync(PLUGIN_DIR)) {
    mkdirSync(PLUGIN_DIR, { recursive: true });
    console.log(`Created ${PLUGIN_DIR}`);
  }

  // Write plugin file
  writeFileSync(PLUGIN_PATH, PLUGIN_CONTENT);

  console.log(`
┌─────────────────────────────────────────────────┐
│                                                 │
│   OpenCode Plugin Setup Complete!               │
│                                                 │
│   Plugin created at:                            │
│   ${PLUGIN_PATH}
│                                                 │
│   Configured hooks:                             │
│   - session.created (session began)             │
│   - session.deleted (session ended)             │
│   - session.idle (work finished)                │
│   - tool.execute.before (tool executing)        │
│                                                 │
│   Next: Run 'npx claude-blocker' to start       │
│                                                 │
└─────────────────────────────────────────────────┘
`);
}

export function isOpenCodePluginConfigured(): boolean {
  if (!existsSync(PLUGIN_PATH)) {
    return false;
  }

  try {
    const content = readFileSync(PLUGIN_PATH, "utf-8");
    return content.includes("ClaudeBlocker") && content.includes("claude-blocker");
  } catch {
    return false;
  }
}

export function removeOpenCodePlugin(): void {
  if (!existsSync(PLUGIN_PATH)) {
    console.log("No OpenCode plugin found, nothing to remove.");
    return;
  }

  try {
    unlinkSync(PLUGIN_PATH);
    console.log("OpenCode Claude Blocker plugin removed.");
  } catch (error) {
    console.error("Error removing OpenCode plugin:", error);
  }
}
